### ISSUE TITLE
pop_mini_RE.sql is removed from gamechanger-web

### ISSUE THREAD

**Issue by neofob** [dod-advana/gamechanger#8]
The file `pop_mini_RE.sql` is removed from `gamechanger-web`, the population of the `responsibilities` table is done somewhere else.

https://github.com/dod-advana/gamechanger/blob/main/deploy/docker-compose/utils.yaml#L135

**Comment by drospond** [comment]
pop_mini_RE.sql was removed because we had a change in the data schema for the responsibility data. The responsibility explorer applies mostly to the policy use case. The init data is only policy data. It allows users to explore entities and responsibilities extracted from a a subset of policies that have responsibility sections. The UI could potentially be repurposed for other use cases but is not currently widely applicable to other use cases. However, if it is still of interest, we could supply an updated pop_mini_RE.sql script.

**Comment by neofob** [comment]
@drospond : Thanks for responding and clarifying the situation. So if the file `pop_mini_RE.sql` is removed for the reason that you mentions, then it should be removed from [`utils.yaml:135`][0], right?

[0]: https://github.com/dod-advana/gamechanger/blob/main/deploy/docker-compose/utils.yaml#L135

**Comment by drospond** [comment]
Correct. We can remove that from the utils.yaml file.

**Comment by neofob** [comment]
OBD
